### ISSUE TITLE
Bus error at FFT sizes other than 16

### ISSUE THREAD

**Issue by twelti** [projectNe10/Ne10#144] opened 2016-11-23 16:10 UTC
Hi,

I'm testing the NE10 library for an FFT application. I have modified the following line in NE10_sample_complex_fft.c:

`#define SAMPLES 16`

by setting SAMPLES to 32. I then build (cross-compile using `NE10_LINUX_TARGET_ARCH "armv7"`), upload the static binary to a Cyclone V with dual ARM A9 processor and run it.

The output will look like this:
````
root@socfpga_cyclone5:~# ./NE10_test_static 
==== Ne10 Samples ===

# Introduction
test_intro[test_add_dynamic]:
	ne10_addc_float:	4.200939 + 0.987757 = 5.188695
	ne10_addc_float:	1.971915 + 0.987757 = 2.959671
	ne10_addc_float:	3.915496 + 0.987757 = 4.903253
	ne10_addc_float:	3.992200 + 0.987757 = 4.979957
	ne10_addc_float:	4.558237 + 0.987757 = 5.545994
test_intro[test_add_static]:
	ne10_addc_float_c:	1.676114 + 3.144355 = 4.820468
	ne10_addc_float_neon:	1.676114 + 3.144355 = 4.820468
	ne10_addc_float_c:	3.841148 + 3.144355 = 6.985502
	ne10_addc_float_neon:	3.841148 + 3.144355 = 6.985502
	ne10_addc_float_c:	1.388874 + 3.144355 = 4.533228
	ne10_addc_float_neon:	1.388874 + 3.144355 = 4.533228
	ne10_addc_float_c:	2.769850 + 3.144355 = 5.914205
	ne10_addc_float_neon:	2.769850 + 3.144355 = 5.914205
	ne10_addc_float_c:	2.386985 + 3.144355 = 5.531340
	ne10_addc_float_neon:	2.386985 + 3.144355 = 5.531340

# Matrix Multiply
[  1.82  4.58  0.71     [  1.21  0.78  0.54     [  8.21 11.07 24.65
   2.57  3.18  3.03   *    0.69  2.00  4.99   =   17.50 10.35 20.58
   4.76  3.59  0.08 ]      4.02  0.65  1.09 ]      8.57 10.97 20.59 ]

[  2.56  1.48  2.47     [  3.86  2.00  1.76     [ 23.29 15.23 21.84
   4.20  3.19  4.86   *    2.63  4.46  4.04   =   43.30 29.50 42.62
   3.06  2.62  1.46 ]      3.85  1.42  4.60 ]     24.35 19.89 22.71 ]

[  0.35  0.43  4.45     [  0.10  1.19  4.25     [  2.42 22.58 14.07
   4.75  0.96  1.74   *    2.29  4.85  1.33   =    3.22 18.19 26.18
   2.63  3.32  0.32 ]      0.32  4.51  2.70 ]      7.95 20.67 16.48 ]


# Complex-to-Complex FFT
Bus error
root@socfpga_cyclone5:~# 
````

I was able to track down the error to somewhere inside `ne10_mixed_radix_fft_forward_float32_neon`.

Is this a known problem, and are there any work-arounds?

Best regards,
Tobias

**Comment by joesavage** [comment] 2016-11-24 09:28
Hey,

I don't believe this is a known problem (at least, it's not known to me!), but I can't seem to reproduce  these issues in my test environment (which is, obviously, completely different to your setup). FFTs of power-of-two lengths have been heavily tested in the Ne10 test suite for a long time, so it seems that this problem is specific to your environment in some way. Not to say that it isn't necessarily a problem with the Ne10 code, just that if this is the case, the issue may conceal itself in other environments.

Are you able to give any further details about where exactly the bus error occurs? It might be worth compiling the library without optimisations to see if the core issue expresses itself in a slightly different manner. Also, have you used these library functions within this setup before, or is this the first time? In the former case, I recently made some changes to the FFT code, so perhaps these have introduced some regressions in certain environments.

**Comment by twelti** [comment] 2016-11-29 13:49
Hi,

This is the first time I'm using these functions, so I am unable to tell if the problem was introduced only recently.

I tried to locate the error but was only able to track it down to the beginning of the function 
`ne10_mixed_radix_fft_forward_float32_neon (fout, fin, cfg->factors, cfg->twiddles, cfg->buffer);`, being called from `ne10_fft_c2c_1d_float32_neon`.

Inside `ne10_mixed_radix_fft_forward_float32_neon`, even the first instruction will not be executed.

If you tell me how to disable optimisations, I will try to investigate further.

We will also try the Ne10 library on a Xilinx Zynq7000 with ARM Cortex-A9 to compare.

**Comment by joesavage** [comment] 2016-11-29 16:20
Hmm... `ne10_mixed_radix_fft_forward_float32_neon` is the meaty, optimised part of the function. I don't recall whether the intrinsics or raw assembly end up getting used in your compilation environment, but the issue is likely to be specific to this. If you want to try compiling without optimisations, you can produce the debug version of the library by passing cmake the `-DDEBUG=ON` option.

With regards to inputs of size 164, the `_neon` version of the function will fail for these as it expects inputs of the form `2^N * 3^M * 5^K` (N, M, K > 0).

**Comment by twelti** [comment] 2016-11-30 08:41
I cleaned the build directory, then ran the following command line, using `-DBUILD_DEBUG=ON` (`-DDEBUG=ON`) was ignored by cmake...

```
$ cmake -DBUILD_DEBUG=ON -DCMAKE_TOOLCHAIN_FILE=../GNUlinux_config.cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-linux-gnueabihf-as
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target architecture: armv7
-- Building type: DEBUG
-- Configuring done
-- Generating done
-- Build files have been written to: /XXXXX/Ne10/build
```
I then type make to build the library. However, when running the test, I don't see any different output.

The output of gdb regarding the bus error (I added some printfs to help locate the error):
```

# Complex-to-Complex FFT
inside complex_fft_sample_main with SAMPLES = 32   1
inside complex_fft_sample_main with SAMPLES = 32   2
inside complex_fft_sample_main with SAMPLES = 32   3
inside complex_fft_sample_main with SAMPLES = 32   4
ne10_fft_c2c_1d_float32_neon 1a
ne10_fft_c2c_1d_float32_neon 2a
ne10_fft_c2c_1d_float32_neon 3a
ne10_fft_c2c_1d_float32_neon 4a
ne10_fft_c2c_1d_float32_neon 4a xx

Program received signal SIGBUS, Bus error.
0x00071d6e in ne10_mixed_radix_fft_forward_float32_neon ()
    at /XXXXX/Ne10/modules/dsp/NE10_fft_float32.neon.s:526
526     /XXXXX/Ne10/modules/dsp/NE10_fft_float32.neon.s: No such file or directory.
```
Since I'm cross-compiling for the Cortex-A9, gdb can't find the source files. Line 526 reads:
```
525 .L_ne10_radix8_butterfly_first_stage_fstride1:
526         BUTTERFLY8X2_WITHOUT_TWIDDLES "FALSE"
527 
528         subs            fstride1, fstride1, #2
529         bgt             .L_ne10_radix8_butterfly_first_stage_fstride1
```

I did not make any modifications to `NE10_fft_float32.neon.s`, so the error should be reproducible with code from the repository. Let me know if you need more details for debugging, since you mentioned that you are testing on a different setup.

I'm still a bit confused regarding the input sizes. Size 16 is working, but in `2^N * 3^M * 5^K` both M and K would be 0. Probably the conditions should be (N, M, K >= 0 and N + M + K > 0)?

**Comment by joesavage** [comment] 2016-11-30 13:53
Oops, quite right about the debug CMake option — I've just updated [building.md](https://github.com/projectNe10/Ne10/blob/master/doc/building.md) to reflect this. And yes, now that I think about it, that size specification is a little odd (though it's what has been listed in the documentation for a long while). If I'm remembering correctly, the input size constraints you outlined are more accurate.

The code still works great in my local test environment, but your failure on line 526 is also telling, as this line [has undergone a recent change](https://github.com/projectNe10/Ne10/commit/d89094e3ae12def7c155b815756ddc2d7c4ddbec#diff-08d4e4a1ad0e450bf85c6da112cb167c). Perhaps I was too hasty in merging this change, for which I can only apologise. It seems the `ADR` pseudo instruction might be causing you some trouble — perhaps due to the range limit [as discussed here](https://github.com/projectNe10/Ne10/pull/84), though I would have expected an assembler error in such a case. Could you try using a [non-cutting-edge release](https://github.com/projectNe10/Ne10/releases)?

**Comment by twelti** [comment] 2016-12-01 15:38
Okay, I've tried abc53aa24022f12a99b4dd8697ce78d9c5a2d46b with the same result: bus error on line 526 of `NE10_fft_float32.neon.s`. So I think your recent change did not introduce this problem.

This is the line that calls the macro `BUTTERFLY8X2_WITHOUT_TWIDDLES "FALSE"` and it has not changed, but the macro has.

If I take the `bf56add` version of `NE10_fft_float32.neon.s`, the same bus error occurs.

Is it possible that my hardware does not support the same version of NEON as yours? I'm testing on an Altera Cyclone V with dual ARM Cortex-A9. What are you running the tests on?

**Comment by joesavage** [comment] 2016-12-01 17:05
Hmm... that's interesting. My understanding is that GNU AS macros are effectively just a textual preprocessing tool, and so the "call site" of `BUTTERFLY8X2_WITHOUT_TWIDDLES` is simply the first instruction within that macro (i.e. whatever is generated by either the `ADR` or `LDR` pseudo-instruction, depending on the version of the codebase). Perhaps it's the case that `gdb`'s line mappings are offset due to the macro expansion? In which case, we might get a better look at the problem here if you are able to examine the assembly instructions around the area of the SIGBUS.

**Comment by twelti** [comment] 2016-12-02 15:06
Things start looking like compiler problems. I tested my binary on a different hardware (Xilinx Zynq7000, Cortex-A9) and it also displays consistent behaviour, bus error on line 526.

I used `gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.1)` to build my binaries.
When using `gcc version 4.8.4 (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1)`, the binary runs on both Zynq7000 and Cyclone V with different FFT sizes without errors.

Regarding the generated assembly code: I struggle to find out how I can get cmake to output the assembly code. Any hint is welcome...

**Comment by joesavage** [comment] 2016-12-02 16:53
Huh, weird. When I test through `qemu-arm` on my local x86 machine I compile with the same compiler version — `gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.1)` — but I'm not seeing any issues in this environment.

I'm not totally sure what the easiest way to massage the CMake files into generating assembly output would be, but if you're able to run the binary in `gdb` you can simply use `layout asm` to view the assembly instructions.

**Comment by twelti** [comment] 2016-12-07 08:22
No luck using `layout asm`, the `gdb` on my test system says `TUI mode not supported`. I listed the source code in `gdb`, but I'm not sure it will help a lot. 

```
(gdb) s
ne10_mixed_radix_fft_forward_float32_neon () at /XXXXX/Ne10/modules/dsp/NE10_fft_float32.neon.s:471
471	        ldr             stage_count, [p_factors]   /* get factors[0]---stage_count */
(gdb) list
466	
467	ne10_mixed_radix_fft_forward_float32_neon:
468	        push            {r4-r12,lr}
469	        vpush           {q4-q7}
470	
471	        ldr             stage_count, [p_factors]   /* get factors[0]---stage_count */
472	        ldr             fstride, [p_factors, #4]   /* get factors[1]---fstride */
473	        add             p_factors, p_factors, stage_count, lsl #3 /* get the address of factors[2*stage_count] */
474	        ldr             radix, [p_factors]                         /* get factors[2*stage_count]--- the first radix */
475	        ldr             mstride, [p_factors, #-4]                  /* get factors[2*stage_count-1]--- mstride */
(gdb) s
472	        ldr             fstride, [p_factors, #4]   /* get factors[1]---fstride */
(gdb) s
473	        add             p_factors, p_factors, stage_count, lsl #3 /* get the address of factors[2*stage_count] */
(gdb) s
474	        ldr             radix, [p_factors]                         /* get factors[2*stage_count]--- the first radix */
(gdb) s
475	        ldr             mstride, [p_factors, #-4]                  /* get factors[2*stage_count-1]--- mstride */
(gdb) s
478	        mov             p_out_ls, p_fout
(gdb) s
482	        cmp             radix, #8
(gdb) list
477	        /* save the output buffer for the last stage  */
478	        mov             p_out_ls, p_fout
479	
480	        /* ---------------the first stage---------------  */
481	        /* judge the radix is 4 or 8  */
482	        cmp             radix, #8
483	        beq             .L_ne10_radix8_butterfly_first_stage
484	
485	        /* ---------------first stage: radix 4  */
486	        mov             count, fstride
(gdb) l
487	        mov             p_fin0, p_fin
488	        mov             p_tmp, p_fout
489	        add             p_fin2, p_fin0, fstride, lsl #4   /* get the address of F[fstride*2] */
490	        add             p_fin1, p_fin0, fstride, lsl #3   /* get the address of F[fstride] */
491	        add             p_fin3, p_fin2, fstride, lsl #3   /* get the address of F[fstride*3] */
492	        vld2.32         {q_in0_01}, [p_fin0:64]!
493	        vld2.32         {q_in2_01}, [p_fin2:64]!
494	        vld2.32         {q_in1_01}, [p_fin1:64]!
495	        vld2.32         {q_in3_01}, [p_fin3:64]!
496	
(gdb) l
497	.L_ne10_radix4_butterfly_first_stage_fstride:
498	        BUTTERFLY4X2_WITHOUT_TWIDDLES "FALSE"
499	
500	        subs            count, count, #2
501	        bgt             .L_ne10_radix4_butterfly_first_stage_fstride
502	
503	        /* swap input/output buffer  */
504	        ldr             tmp0, [sp, #104]
505	        mov             p_fin, p_fout
506	        mov             p_fout, tmp0
(gdb) s
483	        beq             .L_ne10_radix8_butterfly_first_stage
(gdb) s
520	        mov             fstride1, fstride
(gdb) s
521	        mov             p_in1, p_fin
(gdb) s
522	        mov             p_out1, p_fout
(gdb) l
517	
518	        /* ---------------first stage: radix 8  */
519	.L_ne10_radix8_butterfly_first_stage:
520	        mov             fstride1, fstride
521	        mov             p_in1, p_fin
522	        mov             p_out1, p_fout
523	        lsl             fstep, fstride, #3
524	
525	.L_ne10_radix8_butterfly_first_stage_fstride1:
526	        BUTTERFLY8X2_WITHOUT_TWIDDLES "FALSE"
(gdb) l
527	
528	        subs            fstride1, fstride1, #2
529	        bgt             .L_ne10_radix8_butterfly_first_stage_fstride1
530	
531	        lsl             nstep, fstride, #4
532	        sub             stage_count, stage_count, #1
533	        lsr             fstride, fstride, #2
534	
535	        /* swap input/output buffer  */
536	        ldr             tmp0, [sp, #104]
(gdb) s
523	        lsl             fstep, fstride, #3
(gdb) s
526	        BUTTERFLY8X2_WITHOUT_TWIDDLES "FALSE"
(gdb) s

Program received signal SIGBUS, Bus error.
0x00071cae in ne10_mixed_radix_fft_forward_float32_neon ()
    at /XXXXX/Ne10/modules/dsp/NE10_fft_float32.neon.s:526
526	        BUTTERFLY8X2_WITHOUT_TWIDDLES "FALSE"
```

I have found other hints pointing to a local problem with my building setup, I will try to get this fixed and will get back to you.

**Comment by twelti** [comment] 2016-12-07 09:15
For now, I switched back to gcc 4.8.4 because that creates a working binary. Feel free to close this issue, as it seems to have its source in the compiler.

**Comment by joesavage** [comment] 2016-12-07 10:02
Ok, I'll close the issue for now then — feel free to reopen it if you continue to run into problems. Sorry I couldn't be of more help!

**Closed by joesavage** 2016-12-07 10:02 UTC
