### ISSUE TITLE
Android gcc build issues

### ISSUE THREAD

**Issue by ziza69** [projectNe10/Ne10#146] opened 2016-12-27 17:07 UTC
I have run build for Android (latest ndk for Android with gcc 4.9) and I want to tell you what issues I have encountered on the way.

1. Compiler instantly gives: "error: 'for' loop initial declarations are only allowed in C99 or C11 mode", this is easily fixable if you insert **"set(CMAKE_C_FLAGS** "-std=c11")"** in CMakeLists.txt.

2. Gcc does not accept "asm" keyword, and generates rather cryptic error " 'asm' expected before 'asm' (wtf!?)" turns out it should be " \_\_asm\_\_ ". I have solved it by adding "#ifdef GNUC #define asm \_\_asm\_\_"

3. All "simd" functions (i.e. "test_divc, test_mlac, test_mulc, test_rsbc, test_setc, test_subc, test_mulcmatvec" in "NE10Demo" app for Android) generate SIGSEGV error, I have no idea why, maybe some linker issue?

**Comment by joesavage** [comment] 2017-01-12 09:44
Sorry to hear you're having problems, but thanks for reporting them.

With your first issue, it looks like the compiler is assuming an older C standard for some reason — you're quite right that a `std` flag should be able to resolve this, though we probably want to use C99 in this case and must be careful that this flag doesn't propagate into the list of C++ flags. The second issue you're experiencing is then related to the first, as using `asm` within C code is a GNU extension that cannot be used with `-std={c99, c11}`. We could use `__asm__` to fix this as you suggested, but for the time being I'll update the `CMakeLists.txt` file to use `-std=gnu99` instead, resolving both of these issues.

As for your last problem, I'm afraid I have no idea what might be causing this. Would it be possible for you to take a closer look at the execution with a debugger to see exactly where the SIGSEGV occurs?

**Comment by ziza69** [comment] 2017-01-13 17:36
About "simd" functions: I just tried build with -DBUILD_DEBUG=ON option, and there is lots of warnings referencing (suspicious) macros from "macros.h" like:

> NE10_addc.neon.c: In function 'ne10_addc_vec3f_neon':

> NE10_addc.neon.c:61:5: warning: missing braces around initializer [-Wmissing-braces]
>     NE10_DstSrcCst_DO_COUNT_TIMES_VEC3F_NEON

On demo application for Android, first affected function is "test_addc()" and call trace goes like this:
(signal SIGSEGV: invalid address (fault address: 0x121e000):
> Java_com_arm_ne10_demo_MainActivity_NE10RunTest NE10_test_demo.c:62
> test_addc test_suite_math.c:2737
> test_addc_case0 test_suite_math.c:289
>        perftest_thedst_neon = 0x012172e0 (argument 0)
>        perftest_thesrc1 = 0x0120f290 (argument 1)
> ne10_addc_float_neon NE10_addc.neon.c:41
>        dst = 0x0121e000 (argument 0 - this should be 0x012172e0 !!) SIGSEGV
>        src = 0x01215fc0   (argument 1 - this should be 0x0120f290 !!)

I suppose this has to do something with "NE10_DstSrcCst_DO_COUNT_TIMES_FLOAT_NEON" macro like macro somehow changes value of pointers "dst" and "src".

**Comment by joesavage** [comment] 2017-01-16 09:40
Great to hear that you've got everything working. So, to be clear, the issue here is that the Android demo project is by default using the soft floating point ABI (`softfloat`/`softfp`) internally, while Ne10 is using `hardfp`? It looks like the additional flags you passed to the demo project are already present in Ne10's root `CMakeLists.txt` file, but if I'm understanding you correctly you resolved this issue by adding these same arguments to `Ne10/android/NE10Demo/jni/CMakeLists.txt`? I guess the original intention might have been that these flags specified in the root `CMakeLists.txt` somehow trickle down to the Android demo project, but I'm not quite sure how that would work.

**Comment by ziza69** [comment] 2017-01-16 10:06
Yes, you got it right. I guess easiest way would be to just add those flags manually to Android demo project since it is broken in current state.

**Comment by joesavage** [comment] 2017-01-16 10:28
Taking a closer look at this, it seems that the `CMakeLists.txt` file in `Ne10/android/NE10Demo/jni` actually gets invoked automatically, carrying across the desired flags, when building from the root directory and specifying the `android_config.cmake` toolchain file. Presumably this doesn't include building the actual Android application, but it does seem to include building the tests. Would you be able to describe your build process for me so we can try to figure out whether this is the cause?

**Comment by ziza69** [comment] 2017-01-16 10:50
Yes it does but I wanted to play with it and actually copied project in Android studio and well, yes you are correct it does build tests but I did it wrong way :)

**Comment by joesavage** [comment] 2017-01-16 11:15
Ah, I see! In which case, it seems like everything is resolved.

**Closed by joesavage** 2017-01-16 11:15 UTC
