### ISSUE TITLE
Error at calling ne10_fft_alloc_r2c_float32 function in Ne10 library 

### ISSUE THREAD

**Issue by KwakJiWon** [projectNe10/Ne10#139] opened 2016-10-28 08:48 UTC
How are you?
I’m face recognition technology researcher, Korean.
I try to implement the fft computation using Ne10 to speed up in android mobile.
However, my app kill at calling ne10_fft_alloc_r2c_float32 as bellow
 
ne10_fft_r2c_cfg_float32_t realTransCfg = ne10_fft_alloc_r2c_float32(128)
 
How to fix this error?
Please your kind help.
Best,

**Comment by james34602** [comment] 2016-10-28 09:31
The problem may cause by: 
1. Wrong number of allocate memory
2. Unable to obtain correct FFT output
3. Memory overflow caused by forgot to free the memory you have allocated
I have converted a Java FFT app to native FFT, and Ne10 is really fast. I have include the link of my project, this is a 1D FFT: https://github.com/james34602/audio-analyzer-for-android/blob/master/Version_Ne10/jni/JNIFFT.c
You can using 1D FFT to implement 2D FFT.

**Comment by KwakJiWon** [comment] 2016-10-29 00:53
Hi James,
I have fixed this error  by reference your link.
I have added source files in modules/dsp folder in my Makefile.
Before, I try to link static library of Ne10, libNe10.a file.
May be Ne10 static library building has issue.
Best.

**Comment by james34602** [comment] 2016-10-29 01:08
I have never try to compile the static library. If using current method, I cannot link the object that generated by assembly, however intrinsics still works!
If you can make the assembly works, please tell me how!

**Comment by KwakJiWon** [comment] 2016-10-29 01:14
Ne10 static library build work is very simple.
you can reference this link : https://community.arm.com/groups/android-community/blog/2013/09/30/using-ne10-on-android-and-ios

**Comment by KwakJiWon** [comment] 2016-10-29 01:14
Ne10 static library build work is very simple.
you can reference this link : https://community.arm.com/groups/android-community/blog/2013/09/30/using-ne10-on-android-and-ios

**Comment by joesavage** [comment] 2016-11-01 11:19
Is there still an unresolved issue here, or has this been resolved by correctly linking the library?

**Closed** 2016-11-24 11:32 UTC
